{% set name = "pint-pulsar" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d29700f7c1c915115554871a36aa6537333b1e58e697e6250bcfbb8295643c93

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win or py<38]
# Add [skip appveyor] to commit messages to prevent windows from starting at all

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - numpy >=1.17.0
    - astropy >=4.0,!=4.0.1,!=4.0.1.post1
    - scipy >=0.18.1
    - jplephem >=2.6
    - matplotlib-base >=1.5.3
    - emcee >=3.0.1
    - corner >=2.0.1
    - uncertainties
    - pyerfa
    - loguru

# The PyPI package "pint" is a units package whose package name conflicts with ours so they must not both be installed
# This should prevent that
  run_constrained:
    - pint ==9999999999

test:
  imports:
    - pint

about:
  home: https://github.com/nanograv/PINT
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A Pulsar Timing Package, written in Python from scratch
  doc_url: https://nanograv-pint.readthedocs.io/en/latest/
  dev_url: https://github.com/nanograv/PINT

extra:
  recipe-maintainers:
    - paulray
