{% set name = "pint-pulsar" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2faf2a53f22502ee579c59b1d6fffc92a43d54374c22c84abc48e4f53330e196

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win or py<38]
# Add [skip appveyor] to commit messages to prevent windows from starting at all

requirements:
  host:
    - pip
    - python
    - setuptools
    - versioneer

  run:
    - python
    - numpy >=1.23.0
    - astropy-base >=5.0.5
    - scipy >=1.9.0
    - jplephem >=2.6
    - matplotlib-base >=3.4.3
    - emcee >=3.0.1
    - corner >=2.0.1
    - uncertainties
    - pyerfa
    - nestle >=0.2.0
    - loguru
    - numdifftools
    - versioneer

# The PyPI package "pint" is a units package whose package name conflicts with ours so they must not both be installed
# This should prevent that
  run_constrained:
    - pint ==9999999999

test:
  imports:
    - pint

about:
  home: https://github.com/nanograv/PINT
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A Pulsar Timing Package, written in Python from scratch
  doc_url: https://nanograv-pint.readthedocs.io/en/latest/
  dev_url: https://github.com/nanograv/PINT

extra:
  recipe-maintainers:
    - paulray
